src/Entity/File.php
<?php

namespace App\Entity;

use App\Repository\FileRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FileRepository::class)]
class File
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $file_name = null;

    #[ORM\Column]
    private ?\DateTime $date = null;

    #[ORM\ManyToOne(inversedBy: 'files')]
    private ?User $author = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    public function setFileName(string $file_name): static
    {
        $this->file_name = $file_name;

        return $this;
    }

    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    public function setDate(\DateTime $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }
}

src/Form/FileType.php
<?php

namespace App\Form;

use App\Entity\File;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType as SymfonyFileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class FileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
			->add('customName', TextType::class, [
                'label' => 'File Name',
                'mapped' => false,
                'required' => true,
            ])
            ->add('file', SymfonyFileType::class, [
                'label' => 'File',
                'mapped' => false,
                'required' => true,
				
            ])
		;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => File::class,
        ]);
    }
}

src/Controller/FileController.php
<?php
namespace App\Controller;

use App\Entity\File;
use App\Form\FileType;
use App\Repository\FileRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\SecurityBundle\Security;

#[Route('/file')]
class FileController extends AbstractController
{
    #[Route('/', name: 'file_index')]
    public function index(FileRepository $fileRepository): Response
    {
        return $this->render('file/index.html.twig', [
            'files' => $fileRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'file_new')]
    public function new(
        Request $request,
        EntityManagerInterface $em,
        Security $security
    ): Response {
        $file = new File();
        $form = $this->createForm(FileType::class, $file);
        $form->handleRequest($request);
		$customName = $form->get('customName')->getData();

        if ($form->isSubmitted() && $form->isValid()) {

            $uploadedFile = $form->get('file')->getData();

            if ($uploadedFile) {
                $newFilename = $customName.'.'.$uploadedFile->getClientOriginalExtension();

                $uploadedFile->move(
                    $this->getParameter('files_directory'),
                    $newFilename
                );

                $file->setFileName($newFilename);
            }

            $file->setDate(new \DateTime());
            $file->setAuthor($security->getUser());

            $em->persist($file);
            $em->flush();

            return $this->redirectToRoute('file_index');
        }

        return $this->render('file/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'file_show')]
    public function show(File $file): Response
    {
        return $this->render('file/show.html.twig', [
            'file' => $file,
        ]);
    }

    #[Route('/{id}/delete', name: 'file_delete')]
    public function delete(
        Request $request,
        File $file,
        EntityManagerInterface $em
    ): Response {
        if ($this->isCsrfTokenValid('delete'.$file->getId(), $request->request->get('_token'))) {
            $em->remove($file);
            $em->flush();
        }

        return $this->redirectToRoute('file_index');
    }
}

templates/file/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Files{% endblock %}

{% block body %}
	{% for file in files %}
		<img src="{{ asset('uploads/files/' ~ file.fileName) }}">
		<p>
			{{ file.fileName }} -
			{{ file.author.username }} -
			{{ file.date|date('d/m/Y') }}
			<a href="{{ path('file_show', {id: file.id}) }}">Voir</a>
		</p>
	{% endfor %}

	<a href="{{ path('file_new') }}">Ajouter</a>
{% endblock %}

templates/file/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Files{% endblock %}

{% block body %}
	{{ form_start(form, {
		'attr': {'class': 'wiki-form'}
	}) }}
		{{ form_widget(form) }}
		<button>Envoyer</button>
	{{ form_end(form) }}
{% endblock %}

templates/file/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Files{% endblock %}

{% block body %}
	<p>Fichier : {{ file.fileName }}</p>
	<img src="{{ asset('uploads/files/' ~ file.fileName) }}">
	<p>Auteur : {{ file.author.username }}</p>

	<a href="/uploads/files/{{ file.fileName }}" target="_blank">Télécharger</a>

	<form method="post" action="{{ path('file_delete', {id: file.id}) }}">
		<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ file.id) }}">
		<button>Supprimer</button>
	</form>
{% endblock %}